"""
检查 Magento 权限资源名称映射
"""
print("=" * 70)
print("Magento 权限资源名称映射检查")
print("=" * 70)
print()
print("根据错误信息，需要的权限资源是：")
print("  - Magento_Catalog::products")
print("  - Magento_Backend::store")
print()
print("在 Magento 后台，这些权限对应的位置：")
print()
print("1. Magento_Catalog::products")
print("   后台位置：Catalog > Products")
print("   需要勾选：")
print("      ✅ Products (主权限)")
print("      或者：")
print("      ✅ Create")
print("      ✅ Edit")
print("      ✅ Delete")
print("      ✅ View")
print()
print("2. Magento_Backend::store")
print("   后台位置：Stores > Settings > Store")
print("   需要勾选：")
print("      ✅ Store")
print()
print("3. 系统权限")
print("   后台位置：Stores > Settings > Configuration")
print("   需要勾选：")
print("      ✅ Configuration")
print()
print("=" * 70)
print("关键检查点：")
print("=" * 70)
print()
print("1. 权限资源名称必须完全匹配")
print("   - 后台显示的是中文或英文名称")
print("   - 但实际存储的是 'Magento_Catalog::products' 这样的格式")
print()
print("2. 可能的问题：")
print("   - 只勾选了 'View' 但没有勾选 'Create' 或 'Edit'")
print("   - 勾选了父级权限但没有勾选子级权限")
print("   - 权限层级关系不正确")
print()
print("3. 建议的配置方式：")
print("   - 不要只勾选父级，也要勾选具体的子级权限")
print("   - 确保勾选了 'Create', 'Edit', 'Delete', 'View' 全部")
print("   - 或者直接勾选 'Products' 主权限（如果存在）")
print()
print("=" * 70)


