"""
诊断 Magento Integration 配置问题
"""
import os

print("=" * 70)
print("Magento Integration 配置问题诊断")
print("=" * 70)
print()

token = os.getenv('MAGENTO_API_TOKEN', '')
base_url = os.getenv('MAGENTO_BASE_URL', '')

print("1. 配置检查")
print("-" * 70)
print(f"   Base URL: {base_url}")
print(f"   Token: {token[:20]}... (长度: {len(token)})")
print()

if not token or len(token) != 32:
    print("   ❌ Token 格式不正确（应该是 32 位字符串）")
else:
    print("   ✅ Token 格式正确")
print()

print("2. 可能的问题点")
print("-" * 70)
print()
print("   ⚠️  问题 1: 权限设置的时机")
print("      可能遗漏：权限必须在激活 Integration 之前设置")
print("      检查：在 Magento 后台，Integration 是否在设置权限后才激活？")
print()
print("   ⚠️  问题 2: 'All' 权限的实际含义")
print("      可能误解：Magento 的 'All' 可能不包含所有 API 端点")
print("      检查：是否尝试过手动选择具体权限（而不是 'All'）？")
print()
print("   ⚠️  问题 3: Token 生成时机")
print("      可能问题：如果在设置权限之前生成 Token，Token 不包含新权限")
print("      检查：是否在设置权限后重新生成了 Token？")
print()
print("   ⚠️  问题 4: 缓存未清除")
print("      可能遗漏：某些 Magento 版本需要清除特定缓存")
print("      检查：是否在每次配置更改后清除了所有缓存？")
print()

print("3. 建议的解决步骤")
print("-" * 70)
print()
print("   步骤 1: 创建新的 Integration（如果已删除）")
print("           - Name: CJ_Sync")
print("           - 输入管理员密码")
print()
print("   步骤 2: 设置权限（⚠️ 关键：必须在激活之前）")
print("           - 不要选择 'All'，改为手动选择：")
print("             * Catalog > Products (Create, Edit, Delete, View)")
print("             * Stores > Settings > Configuration")
print("             * Stores > Settings > Store")
print("             * Inventory > Inventory > Edit")
print()
print("   步骤 3: 保存 Integration（不要激活）")
print("           - 确认状态为 'Inactive'")
print()
print("   步骤 4: 清除所有缓存")
print("           - php bin/magento cache:flush")
print()
print("   步骤 5: 激活 Integration")
print("           - 点击 'Activate'")
print("           - 如果出现授权提示，点击 'Allow'")
print()
print("   步骤 6: 重新生成 Token")
print("           - 在 Integration 编辑页面，点击 'Reset' 或 'Generate'")
print("           - 复制新的 Token")
print()
print("   步骤 7: 更新 .env 文件")
print("           - MAGENTO_API_TOKEN=新Token")
print()
print("   步骤 8: 重新测试")
print()

print("4. 如果仍然失败")
print("-" * 70)
print()
print("   可能的原因：")
print("   - Magento 版本 bug（某些 2.4.x 版本有权限系统问题）")
print("   - 其他扩展冲突")
print("   - 数据库表损坏")
print()
print("   建议：")
print("   - 检查 Magento 版本")
print("   - 禁用其他扩展测试")
print("   - 联系 Magento 技术支持")
print("   - 或考虑使用管理员 Token（不推荐，安全性低）")
print()

print("=" * 70)
print("详细配置指南请查看: MAGENTO_INTEGRATION_SETUP.md")
print("=" * 70)


